### ISSUE TITLE
How to get e2d3 app for desktop (offline) Excel?

### ISSUE THREAD

**Issue by maphew** [e2d3/e2d3#33]
_I didn't find a forum or tracker for end user issues. My apologies if this is posted in the wrong place._

How can I install e2d3 on desktop Excel 2013, that has no _Connected Service_ link to the Office Store? 

I know _how_ to connect to a Store account, but our business policy doesn't allow it.

**Comment by chimerast** [comment]
Thank you for your question. Here is the correct place to ask it.

Sorry, you can't install e2d3 without accessing to the Office Store.
This is the restriction of ["Office Add-ins"](https://msdn.microsoft.com/en-us/library/office/jj220060.aspx), it's depended on by e2d3.

Cheers,
Hideyuki

**Comment by maphew** [comment]
Oh, I'm sorry to hear that. Our central IT disables linking Desktop Office with the Office Store. I think this is pretty standard practice in large organizations, so you might missing a significant number of potential clients.

_...Later:_ I might have found a path to a solution, use a local **File-based app catalog** instead of the online store:

> IT departments and developers can deploy task pane and content apps to a central file share, where the manifest files will be stored and managed. Users can then obtain apps by specifying this file share as a trusted catalog, or an IT administrator can configure this file share as a trusted catalog by using Group Policy.
> -- [Overview of apps for Office 2013](https://technet.microsoft.com/en-us/library/jj219429.aspx#BKMK_Managing) - Supported distribution points for apps for Office

Perhaps all that's needed is to save the `e2d3_manifest.xml` (or whatever it's proper name is) to `\\server\share\local-office-apps` and have our IT enable it as a trusted location?

Also see: http://superuser.com/questions/994066/install-office-store-app-in-offline-desktop-office

**Comment by maphew** [comment]
More specific instructions: [Create a network shared folder catalog for task pane and content add-ins](https://msdn.microsoft.com/en-us/library/office/fp123503.aspx)

**Comment by chimerast** [comment]
I'm sorry for the late reply.

Yes, you can use e2d3 with the proposed method.
I've tried and succeeded it.

Here is the manifest file of e2d3 (Id is changed).
https://gist.github.com/chimerast/2b2cb846e8885d9de297

Many thanks for trying E2D3!

**Comment by maphew** [comment]
This is great, thank you!
