### ISSUE TITLE
Yo. I notice some error of Simple Bar Chart 

### ISSUE THREAD

**Issue by amogha2050** [e2d3/e2d3#37]
バーチャートのカテゴリー名が、サンプルと自分で追加したのでダブってます！直していただけると、うれしいっす。

Hey guys, I just notice error of Simple bar Chart. when I add new categorical name on chart, sample name still exist. Please check picture attached. Thanks.

![image](https://cloud.githubusercontent.com/assets/15182417/16539005/4fc5cd16-4070-11e6-8266-26701e7cc34b.png)

**Comment by osoken** [comment]
This issue is supposed to be submitted to e2d3-contrib repository. I close this with no change. Thanks for your cooperation :)
