### ISSUE TITLE
さサムネイルひ表示も問題

### ISSUE THREAD

**Issue by hipsrinoky** [e2d3/e2d3#38]
https://www.facebook.com/yuzen.tsuzuki/posts/976138599198644

サムネイルが表示されない事があるらしいです。
スペックの問題ですかね。
時間が出来たら調べてみます。

**Comment by yasunobuigarashi** [comment]
Yamamoto Yu さんが以下のように解決したのでClosed

不具合のあるCommitを取り込んでしまっていたようです。問題は解消いたしましたm(__)m
