### ISSUE TITLE
Office Add-inにD3jsを実装するについて

### ISSUE THREAD

**Issue by JianHe007** [e2d3/e2d3#44]
こんにちは。
今D3JSのTree表示機能をOfficeのAdd-inに実装できないかを検討しておりますが、資料があまりなく困ってるところでこちらを見つけました。とても素晴らしい取り組みです。私も希望が見えるように感じました。
こちらのe2d3はexcelのみd3の対応かと思いますが、自分が作りたいのは、excelも含めてOffice共通のD3Tree表示です。
下記質問のご回答をお願い出来ませんでしょうか。
１、D3.jsのTree表示機能は Office Add-in(Excel, PPT, Word)に実装できるでしょうか。
２、参考になれる資料やURLがあれば、ご教授をお願い出来ませんか。

ご回答、何卒よろしくお願いいたします。
Jason

**Comment by yasunobuigarashi** [comment]
ご質問、ありがとうございます

1 Excel以外にもWord、OneNote、Outlook、PowerPoint、Project
でアドインは作成可能です

2 以下がマイクロソフトの公式開発ドキュメントになります 
https://docs.microsoft.com/ja-jp/office/dev/add-ins/

**Comment by yasunobuigarashi** [comment]
返答したので、Closed
